```{r}
library(pacman)
p_load(data.table, dplyr, ggplot2, cowplot, viridis, scales, reshape, ggpubr,  ggforce, rstatix, RColorBrewer, foreach, EnvStats)
options(scipen=999)
highRes <- "../"
source("../common.R")
dot_size <- 2
theme_set(theme_gray())

d <- readRDS("./dataFig4.RDS")
```

```{r}
###############################################################################
#    Gene modification based on rep existance
# 3A
###############################################################################
fig_fracVSrepBuvimas <- ggplot(d[['A']], aes(modification, Fraction, fill=RepStatus)) +
  geom_boxplot(outlier.shape = 16, outlier.size=0.05, outlier.color = "black", size = 0.1, show.legend = FALSE) +
  geom_point(shape = 21, color = "black" ,size = 0.1, alpha = 0) +
  ylab("fraction") +
  scale_fill_manual(values=col_clTE) +
  labs(color="TE") +
  theme_Publication() +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  facet_grid(cols=vars(Org), scales="free", space="free_x") +
  # expand_limits(y = c(1, 1.15)) +
  theme(axis.title.x = element_blank(), 
        legend.position = "none", 
        panel.spacing=unit(0.3, "lines"),
        legend.title= element_blank(),
        strip.text.x=element_text(face="italic")
        # axis.text.x = element_text(size=rel(1), angle=45, hjust=1, vjust=1)
        )  

p_legend_1 <- fig_fracVSrepBuvimas +
  theme(
    legend.position = "bottom",
    legend.spacing.y = unit(2.0, 'cm'),
    legend.margin = margin(0, 0, 0, 0, unit = "cm"),
  ) +
  guides(fill = guide_legend(override.aes = list(shape = 22, size = 3.5, alpha = 1), nrow = 1, byrow=FALSE))
p_legend_1 <- as_ggplot(get_legend(p_legend_1))
```


## 3B

```{r}
###############################################################################
#    Gene expression based on rep existance
#    3B
###############################################################################
fig_raiskaVSrepBuvimas <- ggplot(d[['B']], aes(Org, TPM_wt, fill=RepStatus)) +
  geom_boxplot(outlier.shape = 16, outlier.size=0.05, outlier.color = "black", show.legend = FALSE, size = 0.1) +
  scale_fill_manual(values=col_clTE) +
  theme_Publication() +
  ylab(expression(paste(log[2], "(TPM+1)"))) + 
  labs(color="TE") +
  theme(axis.title.x = element_blank(), 
        legend.position = "none", 
        panel.spacing = unit(0.3, "lines"),
        axis.text.x = element_text(face="italic"),
        legend.title = element_blank()
      )
```

```{r}
###############################################################################
# Fig exp vs rep and vice versa 
###############################################################################
 fig_exp_rep_pos <- ggarrange(fig_fracVSrepBuvimas, fig_raiskaVSrepBuvimas, 
                       ncol=2,
                      nrow=1, 
                      common.legend = TRUE, 
                      legend="none", 
                      widths = c(3/5, 2/5))
```

## 3C
```{r}
###############################################################################
# Gene modification by repeat position
# 3C
###############################################################################
fig_modRepPos <- ggplot(d[['C']], aes(modification, fraction, fill=tipas)) +
  geom_boxplot(outlier.shape = 16, outlier.size=0.05, outlier.color = "black", size = 0.1) +
  theme_Publication() +
  scale_fill_grey(start=0, end=1) +
  guides(fill=guide_legend(title="Type", nrow=2, byrow=TRUE)) +
  facet_grid(~organism, scales="free", space="free") +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  # expand_limits(y = c(1, 1.15)) +
  theme(axis.title.x = element_blank(), 
        strip.background=element_blank(), 
        legend.position="none", 
        legend.title= element_blank(),
        strip.text.x=element_text(face="italic"), 
        axis.text.x = element_text(size = rel(1), angle = 0, hjust = 0.5, vjust=0))
```


## 3D


```{r}
###############################################################################
# Gene expression by repeat position
# 3D
###############################################################################
fig_raiskaRepPos <- ggplot(d[['D']], aes(organizmas, TPM_wt, fill=tipas)) +
  geom_boxplot(outlier.shape = 16, outlier.size=0.05, outlier.color = "black", size = 0.1, show.legend = FALSE) +
  geom_point(shape = 21, color = "black" ,size = 0.1, alpha = 0) +
  ylab(expression(paste(log[2], "(TPM+1)"))) +
  theme_Publication() +
  scale_fill_grey(start=0, end=1)  +
  guides(color=guide_legend(title="Type", nrow=2, byrow=TRUE)) +
  theme(axis.title.x=element_blank(), 
        axis.text.x=element_text(face="italic"), 
        strip.background=element_blank(), 
        legend.position="none", 
        legend.title= element_blank(),
        strip.text.x=element_text(face="italic")
  ) 
p_legend_2 <- fig_raiskaRepPos +
  theme(
    legend.position = "bottom",
    legend.spacing.y = unit(2.0, 'cm'),
    legend.margin = margin(0, 0, 0, 0, unit = "cm"),
  ) +
  guides(fill = guide_legend(override.aes = list(shape = 22, size = 3.5, alpha = 1), nrow = 2, byrow=FALSE))
p_legend_2 <- as_ggplot(get_legend(p_legend_2))
```

```{r}
###############################################################################
#Exp rep pos figure
###############################################################################
fig_exp_rep <- ggarrange(fig_modRepPos, fig_raiskaRepPos, 
                       ncol=2,
                      nrow=1, 
                      common.legend = TRUE, 
                      legend="none", 
                      widths = c(3/5, 2/5))
```


## 3E

```{r}
###############################################################################
#    Gene expression based on rep existance
#    3E
###############################################################################
fig_grupes <- ggplot(d[['E']], aes(grupe, TPM_wt, fill=cluster)) +
     geom_boxplot(position = position_dodge2(preserve = "single"), outlier.shape = 16, outlier.size=0.05, outlier.color = "black", size = 0.1) +
     ylab(expression(paste(log[2], "(TPM+1)"))) +
     xlab("5fC/5hmC fraction") +
     facet_grid(vardas ~ mC_grupe) + 
     theme_Publication() + 
     scale_fill_manual(values=col_clusters) + 
     scale_x_discrete(labels = c("0"="0", "0-0.1"="", "0.1-0.2"="(0.1-0.2]", "0.2-0.3"="", "0.3-0.4"="(0.3-0.4]", "0.4-0.5"="", "0.5-0.6"="(0.5-0.6]", "0.6-0.7"="", "0.7-0.8"="(0.7-0.8]", "0.8-0.9"="", "0.9-1"="(0.9-1]") ) + 
     theme(legend.position = "none",
           plot.subtitle=element_text(hjust = 0.5),
           plot.tag=element_text(size=18),
           axis.text.x = element_text(size=8, angle=45, hjust=1, vjust=1), 
           # strip.text.x = element_text(size = rel(3.0), vjust = -4.0),
            # panel.margin = unit(-2, "lines"),
           strip.text.y=element_text(angle = 90),
           strip.text.x=element_text(size = 0),
           )      


```



## 3F
```{r}
###############################################################################
#    Expression with extremums
#    
###############################################################################

fig_daug_mazai <- ggplot(d[['F']], aes(grupeX, TPM_wt, fill=cluster_stat)) +
        geom_boxplot(outlier.shape = 16, outlier.size=0.05, outlier.color = "black", size = 0.1) + 
        scale_fill_manual(values=col_clusters) + 
        ylab(expression(paste(log[2], "(TPM+1)"))) +
        stat_pvalue_manual(d[['F_stat']], size=3) +
        expand_limits(y = c(1, 14)) +
        facet_grid(cols=vars(vardas), 
                   space="free",
                   scales="free", 
                   labeller = as_labeller(d[['F_names']])
                   ) +  
        theme_Publication() + 
        theme(
          legend.position = "none",
          legend.title= element_blank(),
          axis.title.x=element_blank(),
          plot.margin=unit(c(2, 2, 2, 8),"mm"),
          strip.text.x=element_text(face="italic"),
          axis.text.x = element_text(size=rel(1), angle=45, hjust=1, vjust=1), 
          strip.text.y=element_text(angle = 0))          
```

## 3G
```{r}
###############################################################################
#    Expression when there is no/low both modifications
#    
###############################################################################
fig_mazai_nera <- ggplot(d[['G']], aes(grupeX, TPM_wt, fill=cluster_stat)) +
        geom_boxplot(outlier.shape = 16, outlier.size=0.05, outlier.color = "black", size = 0.1, show.legend = FALSE) + 
          geom_point(shape = 21, color = "black" ,size = 0.1, alpha = 0) +
        scale_fill_manual(values=col_clusters) + 
        ylab(expression(paste(log[2], "(TPM+1)"))) +
        stat_pvalue_manual(d[['G_stat']], size=3) +
        expand_limits(y = c(1, 16)) +
        facet_grid(cols=vars(vardas), 
                   space="free",
                   scales="free", 
                   labeller = as_labeller(d[['G_names']])
                   ) +
        theme_Publication() + 
        theme(
          legend.position = "none", 
          legend.title= element_blank(),
          axis.title.x=element_blank(),
          strip.text.x=element_text(face="italic"),
          axis.text.x = element_text(size=rel(1), angle=45, hjust=1, vjust=1), 
          strip.text.y=element_text(angle = 0))

p_legend_3 <- fig_mazai_nera +
  theme(
    legend.position = "bottom",
    legend.spacing.y = unit(2.0, 'cm'),
    legend.margin = margin(0, 0, 0, 0, unit = "cm"),
  ) +
  guides(fill = guide_legend(override.aes = list(shape = 22, size = 3.5, alpha = 1), nrow = 1, byrow=FALSE))
p_legend_3 <- as_ggplot(get_legend(p_legend_3))
```

```{r}
#x11(width=7, height=9)

p <- ggdraw() + 
  draw_plot(fig_exp_rep_pos, 10/300, 240/300, 130/300, 50/300) +
  draw_plot(p_legend_1, 0.27, 0.74, 0.1, 0.1) +

  draw_plot(fig_exp_rep, 150/300, 240/300, 140/300, 50/300) +
  draw_plot(p_legend_2, 0.7, 0.732, 0.1, 0.1) +

  draw_plot(fig_grupes, 10/300, 109/300, 280/300, 120/300) +

  draw_plot(fig_daug_mazai, 10/300, 30/300, 160/300, 80/300) +
  draw_plot(fig_mazai_nera, 185/300, 30/300, 105/300, 80/300) +
  draw_plot(p_legend_3, 0.48, 0.033, 0.1, 0.1) +

  # draw_plot(p_legendG, 100/300, 10/300, 100/300, 5/300) +
  draw_text("5mCG fraction", 150/300, 224/300, size=8) +
  draw_text("0", 80/300, 217/300, size=8) +
  draw_text("(0-0.1]", 140/300, 217/300, size=8) +
  draw_text("(0.1-0.5]", 200/300, 217/300, size=8) +
  draw_text("(0.5-0.1]", 260/300, 217/300, size=8) +
  draw_plot_label(
    family = "Helvetica", size = 16,
    LETTERS[1:7],
    c(10/300, 90/300, 150/300, 237/300, 10/300, 10/300, 180/300),
    c(295/300, 295/300, 295/300, 295/300, 227/300, 109/300, 109/300))  

 
ggsave(paste0("../Fig4.pdf"),
  width = 178, height = 220, units = "mm", dpi = 300
)
```
