```{r}
library(pacman)
p_load(data.table, dplyr, ggplot2, rstatix, cowplot, RColorBrewer, lme4, ggpubr)
source("../common.R")
theme_set(theme_gray())
d <- readRDS("dataFigS8.RDS")
```

```{r}
###############################################################################
# Promoters modification versus rep existance
###############################################################################
fig_upsModVSReps <- ggplot(d[[1]], aes(modification, Fraction, color=status)) +
    geom_boxplot(outlier.size=0.5) +
    ylab("fraction") +
    theme_Publication() +
    scale_color_manual(values=col_clTE) +
    expand_limits(y = c(1, 1.15)) +
    theme(
          legend.title= element_blank(),
          legend.position = "bottom",
          strip.text.x=element_text(face="italic"),
          legend.margin = margin(0, 0, 0, 0, unit = "cm"),
          strip.text=element_text(vjust=1, margin = margin(t=0, b=0, r=0, l=0)),
          axis.title.x = element_blank()) +
    facet_grid(~organizmas, scales="free", space="free") +
    annotate("text", x=-Inf, y=1.05, label=paste0("italic(p-value) <= 0.05"), parse=TRUE, size=2.5, hjust=-0.1, vjust=0)
```


```{r}
###############################################################################
# Promoter modification versus gene expression 
###############################################################################
stat.test <- d[[3]]

fig_raiskaVSmod <- ggplot(d[[2]], aes(grupe, TPM, color=cluster_stat)) +
    geom_boxplot(outlier.size=0.5) +
    theme_Publication() + 
    scale_color_manual(values=col_clusters) +
    ylab(expression(paste(log[2], "(TPM+1)"))) +
    ylim(c(0, 5)) +
    facet_grid(meginys ~ ., labeller=label_parsed) +
    stat_pvalue_manual(stat.test[cluster_stat == "In cluster"], size=3, color=col_clusters[1]) +
    stat_pvalue_manual(stat.test[cluster_stat == "Not in cluster"], size=3, color=col_clusters[2]) +
    scale_x_discrete(labels=c("Q0" = "0", "Q1" = "(0-0.25]", "Q2" = "(0.25-0.5]", "Q3" = "(0.5-0.75]", "Q4" = "(0.75-1]")) +
    theme(axis.title.x = element_blank(), 
      strip.background=element_blank(), 
      strip.text.y=element_text(angle = 90), 
      legend.position = "none",
      legend.margin = margin(0, 0, 0, 0, unit = "cm"),
      strip.text=element_text(vjust=0, hjust=0, margin = margin(t=0, b=0, r=0, l=0)),
      legend.title= element_blank(),
      legend.justification = c(1,1)
      ) 

```


```{r vertikalus}
###############################################################################
# Promoters modifications versus cluster status 
###############################################################################
stat.test <- d[[5]]

fig_ModPagalRaiska <- ggplot(d[[4]], aes(grupe, frakcija, color=cluster_stat)) +
    geom_boxplot(outlier.size=0.5) +
    theme_Publication() + 
    ylab("fraction") + 
    scale_color_manual(values=col_clusters) +
    facet_grid(meginys~., labeller=label_parsed) +
    stat_pvalue_manual(stat.test[cluster_stat == "In cluster"], size=3, color=col_clusters[1]) +
    stat_pvalue_manual(stat.test[cluster_stat == "Not in cluster"], size=3, color=col_clusters[2]) +
    theme(axis.title.x = element_blank(), 
      strip.background=element_blank(), 
      strip.text.y=element_text(angle = 90), 
      legend.margin = margin(0, 0, 0, 0, unit = "cm"),
      strip.text=element_text(vjust=0, hjust=0.5, margin = margin(t=0, b=0, r=0, l=0)),
      legend.position="bottom", 
      legend.title= element_blank()
      )    
legenda <- as_ggplot(get_legend(fig_ModPagalRaiska))      
fig_ModPagalRaiska <- fig_ModPagalRaiska + theme(legend.position="none")

```


```{r}
#x11(width=7, height=7)
p <- ggdraw() +
  draw_plot(fig_upsModVSReps, 12/300, 190/300 , 170/300, 100/300) +
  draw_plot(fig_ModPagalRaiska, 190/300, 15/300, 100/300, 265/300) +
  draw_plot(fig_raiskaVSmod, 10/300, 15/300, 170/300, 170/300) +
  draw_plot(legenda, 5/300, 5/300, 1, 10/300 ) + 
  draw_plot_label(
    family = "Helvetica", size = 16,
    LETTERS[1:3],
    c(8/300, 190/300, 8/300),
    c(295/300, 295/300, 198/300))  


ggsave(paste0("../FigS8.tiff"),
  width = 178, height = 180, units = "mm", dpi = 300
)

```