```{r}
library(pacman)
p_load(data.table, dplyr, ggplot2, cowplot, viridis, scales, reshape, ggpubr, ggforce)
highRes <- "../"
source("../common.R")
dot_size <- 2
theme_set(theme_gray())
```


```{r}
# A part - mass spec
# B part - barplot 
# C part - barplot
# D plot - barplot

###############################################################
# A part
#  schema
###############################################################

###############################################################
# B part
#
d <- fread("../Fig2.txt") %>% 
  .[, Fraction := factor(Fraction, levels=c("total", "large polyA-depleted", "small", "polyA"), labels=c("total", "large\npolyA-depleted", "small", "polyA"))] %>% 
  .[, Mod := factor(Mod, levels=c("5mrC untreated", "5mrC vitC 2d", "5mrC vitC 5d", "5hmrC untreated", "5hmrC vitC 2d", "5hmrC vitC 5d", "5carC-der untreated", "5carC-der vitC 2d", "5carC-der vitC 5d"))]
names(col_nine) <- unique(d$Mod)

fig_b <- d[Fig == "2B", ] %>%
 .[Mod == "5carC-der vitC 2d" & Fraction == "polyA", markeris := "IMAM"] %>% 
 .[markeris == "IMAM", `:=` (Vid=0.0000001, kiek=0.0000015)] %>% ## I need an empty column..
 .[Vid != 0 | markeris == "IMAM", ] %>% 
 .[Stdev == 0, Stdev := NA] %>% 
 ggplot(data = .) + 
  geom_segment(aes(x = Mod, 
                   xend = Mod, 
                   y = 0.000001, 
                   yend = Vid, 
                   colour = Mod
                   ),
               size = 3) +
  geom_point(aes(x=Mod, y=kiek, color=Mod), size=dot_size) +                  
  scale_y_log10(name = "% of G, log scale",
                breaks = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1), 
                labels = c(expression(paste(10^-6)), expression(paste(10^-5)), expression(paste(10^-4)), expression(paste(10^-3)), expression(paste(10^-2)), expression(paste(10^-1)), expression(paste(10^-0))), 
                limits = c(0.000001, 1), 
                position = "left") +
  geom_errorbar(aes(x = Mod, ymin=Vid-Stdev, ymax=Vid+Stdev), width=.4) +                   
  # scale_color_manual(values = rev(c("#fec44f", "#fe9929", "#d95f0e", "#9ecae1", "#6baed6", "#3182bd", "#df65b0", "#dd1c77", "#980043"))) +
  scale_color_manual(values = col_nine) +
  theme_Publication() +
  theme(axis.text.x=element_blank(),
        axis.title.x=element_blank(), 
        legend.position="none",
        legend.spacing.y = unit(0.3, 'cm'),
        axis.ticks.x=element_blank(), 
        strip.background = element_blank(),
        strip.placement = "outside", 
        strip.text=element_text(vjust=1, margin = margin(t=0)),
        plot.title = element_text(size = 8, vjust = -3, hjust=0.1)) +
  guides(color = guide_legend(byrow = TRUE)) +       
  facet_grid(~Fraction, scales="free_x", space="free_x", switch="both") +
  ggtitle(expression(paste(italic("C. cinerea"), " RNA")))

p_legendB <- fig_b +
  theme(
    legend.title = element_blank(), 
    legend.position = "right",
    legend.spacing.y = unit(0.2, 'cm'),
    legend.margin = margin(0, 0, 0, 0, unit = "cm"),
    legend.key.height = unit(0.1, 'cm'),
    legend.key.width = unit(0.1, 'cm')
  ) +
  guides(color = guide_legend(title.position = "left",
                                title.vjust = 1,
                                byrow = TRUE
                                #label.position = "bottom")
                                ))
p_legendB <- as_ggplot(get_legend(p_legendB)) 
###############################################################

###############################################################
# C part
#
d <- fread("../Fig2.txt") %>% 
  .[, Fraction := factor(Fraction, levels=c("28S, 18S  rRNA", "5.8S rRNA", "5S  rRNA", "tRNA", "<tRNA ≧22 nt", "<22 nt"),
    labels = c(
      "28S,\n18S\nrRNA", "5.8S\nrRNA",
      "5S\nrRNA", "tRNA",
      # "<tRNA\n\u2265 22 nt", 
      "<tRNA\n      nt", 
      "<22 nt"
    )
)] %>% 
  .[, Mod := factor(Mod, levels=c("5mrC untreated", "5mrC vitC 2d", "5mrC vitC 5d", "5hmrC untreated", "5hmrC vitC 2d", "5hmrC vitC 5d", "5carC-der untreated", "5carC-der vitC 2d", "5carC-der vitC 5d"))]

fig_c <- d[Fig == "2C", ] %>% 
 .[(Mod == "5carC-der vitC 2d" & Fraction == "5.8S\nrRNA") , markeris := "IMAM"] %>% 
 .[(Mod == "5carC-der vitC 2d" & Fraction == "tRNA") , markeris := "IMAM"] %>% 
 .[markeris == "IMAM", Vid:=0.0000001] %>% 
 .[Vid != 0 | markeris == "IMAM", ] %>% 
 .[markeris == "IMAM", kiek:=0.0000015] %>% 
 .[Stdev == 0, Stdev := NA] %>% 
 .[(Mod == "5carC-der vitC 2d" & Fraction == "<22 nt"), `:=` (kiek=0.0004, markeris="IMAM")] %>%
 .[(Mod == "5carC-der untreated" & Fraction == "<22 nt"), `:=` (kiek=0.00006, markeris="IMAM2")] %>%
 ggplot(data = .) + 
  geom_segment(aes(x = Mod, 
                   xend = Mod, 
                   y = 0.000001, 
                   yend = Vid, 
                   colour = Mod
                   ),
               size = 3) +
  geom_point(aes(x=Mod, y=kiek, color=Mod, shape=markeris), size=dot_size) +   
  scale_shape_manual(values=c(19, 8)) +            
  scale_y_log10(name = "% of G, log scale",
                breaks = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1), 
                labels = c(expression(paste(10^-6)), expression(paste(10^-5)), expression(paste(10^-4)), expression(paste(10^-3)), expression(paste(10^-2)), expression(paste(10^-1)), expression(paste(10^-0))), 
                limits = c(0.000001, 1.5), 
                position = "left") +
  geom_errorbar(aes(x = Mod, ymin=Vid-Stdev, ymax=Vid+Stdev), width=.4) +       
  # scale_color_manual(values = rev(c("#fec44f", "#fe9929", "#d95f0e", "#9ecae1", "#6baed6", "#3182bd", "#df65b0", "#dd1c77", "#980043"))) +
  theme_Publication() +
    scale_color_manual(values = col_nine) +
  theme(axis.text.x=element_blank(),
        axis.title.x=element_blank(), 
        legend.position="none",
        axis.ticks.x=element_blank(), 
        strip.background = element_blank(),
        strip.placement = "outside", 
        strip.text=element_text(vjust=1, margin = margin(t=0)),
        plot.title = element_text(size = 8, vjust = -3, hjust=0.1)) +
  facet_grid(~Fraction, scales="free_x", space="free_x", switch="both") +
  ggtitle(expression(paste(italic("C. cinerea"), " RNA")))

###############################################################

###############################################################
# D part
#
d <- fread("../data/Fig2.txt") %>% 
  .[, Fraction := factor(Fraction, levels=c("total", "large polyA-depleted", "small", "polyA"), labels=c("total", "", "small", "polyA"))] %>% 
  .[, Mod := factor(Mod, levels=c("5mrC untreated", "5mrC vitC 2d", "5mrC vitC 5d", "5hmrC untreated", "5hmrC vitC 2d", "5hmrC vitC 5d", "5carC-der untreated", "5carC-der vitC 2d", "5carC-der vitC 5d"))]

fig_d <- d[Fig == "2D", ] %>%
 .[Vid != 0, ] %>% 
 .[Stdev == 0, `:=` (Stdev = NA)] %>% 
 .[Fraction == "small" & Mod == "5carC-der vitC 2d", kiek:=0.00002] %>%
 .[Fraction == "polyA" & Mod == "5hmrC vitC 2d", kiek:=0.008] %>% 
 ggplot(data = .) + 
  geom_segment(aes(x = Mod, 
                   xend = Mod, 
                   y = 0.000001, 
                   yend = Vid, 
                   colour = Mod
                   ),
               size = 3) +
  geom_point(aes(x=Mod, y=kiek, color=Mod), shape=8, size=dot_size) +                  
  scale_y_log10(name = "% of G, log scale",
                breaks = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1), 
                labels = c(expression(paste(10^-6)), expression(paste(10^-5)), expression(paste(10^-4)), expression(paste(10^-3)), expression(paste(10^-2)), expression(paste(10^-1)), expression(paste(10^-0))), 
                limits = c(0.000001, 1.3), 
                position = "left") +
  geom_errorbar(aes(x = Mod, ymin=Vid-Stdev, ymax=Vid+Stdev), width=.4) +       
  # scale_color_manual(values = rev(c("#fec44f", "#fe9929", "#d95f0e", "#9ecae1", "#6baed6", "#3182bd", "#df65b0", "#dd1c77", "#980043"))) +
  theme_Publication() +
    scale_color_manual(values = col_nine) +
  theme(axis.text.x=element_blank(),
        axis.title.x=element_blank(), 
        legend.position="none",
        axis.ticks.x=element_blank(), 
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text=element_text(vjust=1, margin = margin(t=0)),
        plot.title = element_text(size = 8, vjust = -3, hjust=0.1)) +
  facet_grid(~Fraction, scales="free_x", space="free_x", switch="both")  +
  ggtitle(expression(paste(italic("L. bicolor"), " RNA")))         

######################################sz#########################

```

```{r}
###############################################################
# Full plot
#x11(width=7, height=6.3)
tmp_gt <-
 ggplot() +
  geom_point(
    aes(1,1,), size =1,shape = 1, color = "white"
  ) +
  theme_void() +
  labs(x = expression(phantom(x) >=22),y = NULL) +
  theme(axis.title = element_text(size = 8, color = "black"),)

p <- ggdraw() + 
  draw_image(paste0("mass_specas.png"), 10/300, 210/300, 280/300, 75/300) +
  draw_plot(fig_b, 10/300, 110/300, 199/300, 90/300) +
  draw_plot(fig_c, 10/300, 20/300, 175/300, 95/300) + 
  draw_plot(fig_d, 190/300, 33/300, 100/300, 80/300) +
  draw_plot(p_legendB, 200/300, 95/300, 100/300, 140/300) +
  draw_text("large\npolyA-\ndepleted", 245/300, 34/300, size=8, lineheight = 0.8,) +
  draw_plot(tmp_gt, 132.8/300, 31.6/300, 1/200, 1/200) +
  draw_plot_label(
    family = "Helvetica", size = 16,
    LETTERS[1:4],
    c(3/100, 3/100, 3/100, 190/300),
    c(290/300, 207/300, 115/300, 115/300))  

ggsave(paste0(highRes, "../Fig22.pdf"), plot=p,
  width = 178, height = 160, units = "mm", dpi = 300
)


```





